default:
  tags:
    - arch:amd64
    - size:medium
  before_script:
    - npm i -g npm
    - echo node $(node --version)
    - echo npm $(npm --version)
    - npm ci --cache .npm --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_PROJECT_NAME}
    paths:
      - .npm/

variables:
  # Disable AWS profile in GitLab Runner to avoid unintended access during `cdk synth`.
  # If you use your AWS account to deploy CDK apps, you should remove this, then set secret varibales in GitLab CI/CD settings from web.
  AWS_PROFILE: ''
  AWS_DEFAULT_REGION: ''
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  NODE_OPTIONS: --max_old_space_size=12288
  # Limit Jest parallel workers to reduce memory usage
  JEST_MAX_WORKERS: 2

.node-build: &node-build
  - npm run lint:ci
  - npm run format:ci
  - npm run build --workspaces
  - npm run test --workspaces -- --maxWorkers=2
#  - npm run synth:dev --workspaces

build-node20:
  stage: build
  image: node:20
  script:
    - *node-build

build-node22:
  stage: build
  image: node:22
  script:
    - *node-build

build-node24:
  stage: build
  image: node:24
  script:
    - *node-build
